import type { Metadata } from "next";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { WhatsAppFloat } from "../components/WhatsAppFloat";

export const metadata: Metadata = { title: "Custom Brass Fittings Manufacturing Capabilities", description: "Learn how CIXI LINHAO supports custom brass garden hose fittings from drawings, samples and specifications through production and quality coordination.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  return <><Header /><main><section className="page-hero about-hero"><div className="container"><span className="eyebrow eyebrow-light">About CIXI LINHAO</span><h1>A focused partner for custom brass garden hose fittings.</h1><p>We support product selection, drawing and sample review, specification alignment, quality follow-up and export communication for brass hose fitting programs.</p></div></section><section className="section"><div className="container about-intro"><div><span className="eyebrow">Our focus</span><h2>Brass hose fitting programs for global B2B buyers.</h2></div><div><p>CIXI LINHAO serves importers, distributors, retailers and private-label operators seeking brass hose fittings and clear commercial communication.</p><p>Our scope covers connectors, threaded adapters, couplings, swivels, elbows, splitters, shut-off valves, nozzle components, hose reel fittings and custom brass parts.</p></div></div></section><section className="section oem-detail" id="oem"><div className="container"><div className="section-heading centered-heading"><span className="eyebrow">OEM / ODM support</span><h2>Customization that stays commercially practical.</h2></div><div className="capability-grid" id="capabilities">{[["Product", "Materials, dimensions, thread options, colors and assortment planning."],["Branding", "Logo application, labels, instruction sheets and retail presentation."],["Packaging", "Polybag, card, box, mailer, tool bag and customized set configurations."],["Export", "Carton marks, documents, inspection coordination and shipment follow-up."]].map(([title,text])=><article key={title}><span>{title.slice(0,1)}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="section quality-section" id="quality"><div className="container feature-story-grid"><div className="quality-copy"><span className="eyebrow">Quality coordination</span><h2>Verify what matters before products leave.</h2><p>Quality requirements are aligned to the approved product and packaging specification, with checkpoints selected for the item and order.</p><ul className="check-list"><li>Material and appearance confirmation</li><li>Dimensions, thread and compatibility checks</li><li>Function, assembly and leak-related checks where applicable</li><li>Logo, barcode, label and packaging review</li><li>Quantity, carton and shipment documentation checks</li></ul></div><div className="quality-card"><strong>BUYER FILE</strong><h3>Your approval standard</h3><p>Reference sample</p><p>Specification sheet</p><p>Packaging artwork</p><p>Inspection points</p><a className="button" href="/contact">Start a project</a></div></div></section></main><Footer /><WhatsAppFloat /></>;
}
